"""Add missing fields to Case model

Revision ID: 620c5309d8ca
Revises: b01cb1143cf0
Create Date: 2025-06-05 00:43:43.062998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620c5309d8ca'
down_revision: Union[str, None] = 'b01cb1143cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('generated_draft', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('applicable_laws', sa.JSON(), nullable=True))
    op.add_column('cases', sa.Column('suggested_ngos', sa.JSON(), nullable=True))
    op.add_column('cases', sa.Column('next_steps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'next_steps')
    op.drop_column('cases', 'suggested_ngos')
    op.drop_column('cases', 'applicable_laws')
    op.drop_column('cases', 'generated_draft')
    # ### end Alembic commands ###
