"""Add case_id field to Case model

Revision ID: 71afacfb8163
Revises: 620c5309d8ca
Create Date: 2025-06-05 00:44:51.791545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71afacfb8163'
down_revision: Union[str, None] = '620c5309d8ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_column('cases', 'case_id')
    # ### end Alembic commands ###
