"""Initial migration with UUID and JSONB

Revision ID: ad43aec9abc4
Revises: 
Create Date: 2025-06-25 23:47:09.049751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad43aec9abc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_draft', sa.Text(), nullable=True),
    sa.Column('applicable_laws', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_ngos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_case_applicable_laws_gin', 'cases', ['applicable_laws'], unique=False, postgresql_using='gin')
    op.create_index('idx_case_category_status', 'cases', ['category', 'status'], unique=False)
    op.create_index('idx_case_created_status', 'cases', ['created_at', 'status'], unique=False)
    op.create_index('idx_case_next_steps_gin', 'cases', ['next_steps'], unique=False, postgresql_using='gin')
    op.create_index('idx_case_suggested_ngos_gin', 'cases', ['suggested_ngos'], unique=False, postgresql_using='gin')
    op.create_index('idx_case_user_status', 'cases', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_cases_category'), 'cases', ['category'], unique=False)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_title'), 'cases', ['title'], unique=False)
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_case_rating', 'feedback', ['case_id', 'rating'], unique=False)
    op.create_index('idx_feedback_created', 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_case_id'), 'feedback', ['case_id'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_rating'), 'feedback', ['rating'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_rating'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_case_id'), table_name='feedback')
    op.drop_index('idx_feedback_created', table_name='feedback')
    op.drop_index('idx_feedback_case_rating', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_title'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_category'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_index('idx_case_user_status', table_name='cases')
    op.drop_index('idx_case_suggested_ngos_gin', table_name='cases', postgresql_using='gin')
    op.drop_index('idx_case_next_steps_gin', table_name='cases', postgresql_using='gin')
    op.drop_index('idx_case_created_status', table_name='cases')
    op.drop_index('idx_case_category_status', table_name='cases')
    op.drop_index('idx_case_applicable_laws_gin', table_name='cases', postgresql_using='gin')
    op.drop_table('cases')
    # ### end Alembic commands ###
